# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(841, 716)
        self.centralwidget = QtWidgets.QWidget(UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.regsiter = QtWidgets.QWidget()
        self.regsiter.setObjectName("regsiter")
        self.layoutWidget = QtWidgets.QWidget(self.regsiter)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 721, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.key_generation_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.key_generation_checkbox.setText("")
        self.key_generation_checkbox.setObjectName("key_generation_checkbox")
        self.gridLayout.addWidget(self.key_generation_checkbox, 5, 0, 1, 1)
        self.username_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.username_input.setObjectName("username_input")
        self.gridLayout.addWidget(self.username_input, 2, 1, 1, 2)
        self.lname_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.lname_input.setObjectName("lname_input")
        self.gridLayout.addWidget(self.lname_input, 1, 1, 1, 2)
        self.fname_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.fname_input.setObjectName("fname_input")
        self.gridLayout.addWidget(self.fname_input, 0, 1, 1, 2)
        self.password_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 3, 1, 1, 2)
        self.file_selection_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.file_selection_btn.setObjectName("file_selection_btn")
        self.gridLayout.addWidget(self.file_selection_btn, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 1, 1, 2)
        self.public_key_file_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.public_key_file_input.setEnabled(False)
        self.public_key_file_input.setObjectName("public_key_file_input")
        self.gridLayout.addWidget(self.public_key_file_input, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 3, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.regsiter)
        self.splitter_2.setGeometry(QtCore.QRect(220, 450, 170, 27))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.register_btn = QtWidgets.QPushButton(self.splitter_2)
        self.register_btn.setObjectName("register_btn")
        self.tabWidget.addTab(self.regsiter, "")
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.layoutWidget1 = QtWidgets.QWidget(self.login)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 40, 271, 381))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.password_login_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.password_login_input.setObjectName("password_login_input")
        self.gridLayout_2.addWidget(self.password_login_input, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)
        self.username_login_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.username_login_input.setObjectName("username_login_input")
        self.gridLayout_2.addWidget(self.username_login_input, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 2)
        self.splitter = QtWidgets.QSplitter(self.login)
        self.splitter.setGeometry(QtCore.QRect(160, 450, 336, 27))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.login_btn = QtWidgets.QPushButton(self.splitter)
        self.login_btn.setObjectName("login_btn")
        self.keys_dir_btn = QtWidgets.QPushButton(self.login)
        self.keys_dir_btn.setGeometry(QtCore.QRect(354, 180, 381, 38))
        self.keys_dir_btn.setObjectName("keys_dir_btn")
        self.label_directory = QtWidgets.QLabel(self.login)
        self.label_directory.setGeometry(QtCore.QRect(341, 251, 481, 41))
        self.label_directory.setText("")
        self.label_directory.setObjectName("label_directory")
        self.tabWidget.addTab(self.login, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 481, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.text_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.text_input.setObjectName("text_input")
        self.gridLayout_3.addWidget(self.text_input, 1, 0, 1, 1)
        self.text_output = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.text_output.setObjectName("text_output")
        self.gridLayout_3.addWidget(self.text_output, 0, 0, 1, 1)
        self.send_btn = QtWidgets.QPushButton(self.tab)
        self.send_btn.setGeometry(QtCore.QRect(510, 430, 221, 41))
        self.send_btn.setObjectName("send_btn")
        self.signCheck = QtWidgets.QCheckBox(self.tab)
        self.signCheck.setGeometry(QtCore.QRect(500, 380, 239, 26))
        self.signCheck.setObjectName("signCheck")
        self.clientsLists = QtWidgets.QComboBox(self.tab)
        self.clientsLists.setGeometry(QtCore.QRect(500, 110, 239, 36))
        self.clientsLists.setObjectName("clientsLists")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        UserWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 34))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        UserWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserWindow)
        self.statusbar.setObjectName("statusbar")
        UserWindow.setStatusBar(self.statusbar)
        self.actionMinimize = QtWidgets.QAction(UserWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionFull_screen = QtWidgets.QAction(UserWindow)
        self.actionFull_screen.setObjectName("actionFull_screen")
        self.actionWhat_s_this = QtWidgets.QAction(UserWindow)
        self.actionWhat_s_this.setObjectName("actionWhat_s_this")
        self.actionWho_are_We = QtWidgets.QAction(UserWindow)
        self.actionWho_are_We.setObjectName("actionWho_are_We")
        self.actionClose = QtWidgets.QAction(UserWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen_new_window = QtWidgets.QAction(UserWindow)
        self.actionOpen_new_window.setObjectName("actionOpen_new_window")
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(UserWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)
        UserWindow.setTabOrder(self.fname_input, self.lname_input)
        UserWindow.setTabOrder(self.lname_input, self.username_input)
        UserWindow.setTabOrder(self.username_input, self.password_input)
        UserWindow.setTabOrder(self.password_input, self.public_key_file_input)
        UserWindow.setTabOrder(self.public_key_file_input, self.file_selection_btn)
        UserWindow.setTabOrder(self.file_selection_btn, self.key_generation_checkbox)
        UserWindow.setTabOrder(self.key_generation_checkbox, self.register_btn)
        UserWindow.setTabOrder(self.register_btn, self.username_login_input)
        UserWindow.setTabOrder(self.username_login_input, self.password_login_input)
        UserWindow.setTabOrder(self.password_login_input, self.login_btn)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "Secure mail transfert application"))
        self.label_4.setText(_translate("UserWindow", "Password"))
        self.label_3.setText(_translate("UserWindow", "login"))
        self.file_selection_btn.setText(_translate("UserWindow", "browse"))
        self.label_2.setText(_translate("UserWindow", "Last name"))
        self.label_13.setText(_translate("UserWindow", "i have no key , generate one for me please"))
        self.label.setText(_translate("UserWindow", "First name"))
        self.label_11.setText(_translate("UserWindow", "Key file"))
        self.register_btn.setText(_translate("UserWindow", "Register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.regsiter), _translate("UserWindow", "register "))
        self.label_8.setText(_translate("UserWindow", "Username"))
        self.label_9.setText(_translate("UserWindow", "Password"))
        self.login_btn.setText(_translate("UserWindow", "Login"))
        self.keys_dir_btn.setText(_translate("UserWindow", "Select keys directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.login), _translate("UserWindow", "login    "))
        self.send_btn.setText(_translate("UserWindow", "Send"))
        self.signCheck.setText(_translate("UserWindow", "Sign your Message"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UserWindow", "Comunication"))
        self.menuFile.setTitle(_translate("UserWindow", "Fi&le"))
        self.actionMinimize.setText(_translate("UserWindow", "&Minimize"))
        self.actionFull_screen.setText(_translate("UserWindow", "&Full screen"))
        self.actionWhat_s_this.setText(_translate("UserWindow", "&What\'s this"))
        self.actionWho_are_We.setText(_translate("UserWindow", "W&ho are We ?"))
        self.actionClose.setText(_translate("UserWindow", "&close"))
        self.actionOpen_new_window.setText(_translate("UserWindow", "&open new window"))
        from client.actions import Action
        self.action = Action(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserWindow = QtWidgets.QMainWindow()
    ui = Ui_UserWindow()
    ui.setupUi(UserWindow)
    app.lastWindowClosed.connect(ui.action.closeAll)
    UserWindow.show()
    sys.exit(app.exec_())

